### ISSUE TITLE
Get peripherals with pagination

### ISSUE THREAD

**Issue by PaulinaAldaco** [estebansanch/Project.PeripheralLoan#60]
Add get request to get peripherals and add pagination using limit and offset. Connect to frontend.

**Comment by PaulinaAldaco** [comment]
Pagination complete in back and front. Missing showing pulled devices in front, to be done by @DavidVelazquez584

**Comment by DavidVelazquez584** [comment]
All frontend and backend finished, all devices or peripherals showing with the dabase data and pagination working
